version: "3.9"
volumes:
  db-store:
services:
  go:
    build:
      context: .
      dockerfile: ./build/docker/go/Dockerfile
    container_name: go
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/src
  db:
    image: mysql:8.3
    env_file:
      - ./cmd/app/.env
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
