version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: ./build/docker/go/Dockerfile
    container_name: go
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/src
      - ./.aws:/root/.aws
  mock-cognito-cli:
    image: public.ecr.aws/aws-cli/aws-cli
    container_name: mock-cognito-cli
    tty: true
    environment:
      ENDPOINT_URL: http://mock-cognito-server:4000
      COGNITO_USER_EMAIL: sample@example.com # テストユーザー
      COGNITO_USER_PASSWORD: Test@0113 # テストユーザーのパスワード
    entrypoint: sh -c "chmod +x /workdir/bash/create-user-pool.sh && /workdir/bash/create-user-pool.sh && tail -f /dev/null"
    ports:
      - "4010:4010"
    depends_on:
      - mock-cognito-server
    volumes:
      - ./build/docker/aws/mock-cognito-cli/bash:/workdir/bash
      - ./.aws:/root/.aws
      - ./build/docker/aws/mock-cognito-cli/output:/output
  mock-cognito-server:
    image: motoserver/moto:latest
    container_name: mock-cognito-server
    environment:
      MOTO_PORT: 4000
    ports:
      - "4000:4000"
